//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OutBarDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MULTIVIEW_FORM1             101
#define IDR_OUTBARDEMO                  108
#define IDR_MAINFRAME                   128
#define IDR_OUTBARTYPE                  129
#define IDD_MULTIVIEW_FORM2             130
#define IDB_SPLASH                      131
#define IDD_MULTIVIEW_FORM3             131
#define IDB_IMAGELIST                   132
#define IDR_DRAW                        132
#define IDD_MULTIVIEW_FORM4             132
#define IDB_SMALL_IMAGELIST             133
#define IDD_SETTING                     133
#define IDR_CJWEBHTML                   135
#define IDD_EDHJ_SET                    137
#define IDD_UP_EXTEND                   140
#define IDD_IEBAR                       142
#define IDI_HIDE_BTN                    143
#define IDC_RESIZE                      144
#define IDD_PRETRIM                     147
#define IDD_MYDLG                       149
#define IDD_ABNORMALCACU                150
#define IDD_NOTICE                      152
#define IDD_Flash                       153
#define IDD_RDYT_SET                    154
#define IDI_STAMP                       156
#define IDD_RDYH_SET                    157
#define IDD_MAG_THROP                   159
#define IDD_STATIC_TEST                 161
#define IDD_SMOOTH_SET                  162
#define IDD_SUFF_GRAP                   164
#define IDD_GRAVITY_QT                  166
#define IDC_NODRAGGING                  268
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_EDIT6                       1005
#define IDC_EDIT7                       1006
#define IDC_EDIT8                       1007
#define IDC_EDIT9                       1008
#define IDC_EDIT10                      1009
#define IDC_COMBO1                      1013
#define IDC_AI                          1020
#define IDC_A                           1021
#define IDC_FILEIN                      1022
#define IDC_FILEOUT                     1023
#define IDC_BROWSE                      1024
#define IDC_FILEOPEN                    1026
#define IDC_RADIO1                      1028
#define IDC_RADIO2                      1029
#define IDC_RADIO3                      1030
#define IDC_RADIO4                      1032
#define IDC_RADIO5                      1033
#define IDC_RADIO6                      1034
#define IDC_BUTTON1                     1041
#define IDC_BUTTON2                     1042
#define IDC_BUTTON3                     1044
#define IDC_FILE_EDIT                   1044
#define IDC_PARA_FORM                   1044
#define IDC_CHECK1                      1045
#define IDC_ABNORMALCACU                1045
#define IDC_PRETRIM                     1045
#define IDC_MYDLG                       1045
#define IDC_CHECK2                      1046
#define IDC_RIVISE                      1046
#define IDC_CHECK3                      1047
#define IDC_XYDATA                      1047
#define IDC_CHECK4                      1048
#define IDC_OPENDATA                    1049
#define IDC_GRAVITY_TYPE                1050
#define IDC_PRETRIM_OPEN                1051
#define IDC_PRETRIM_INFILE              1052
#define IDC_PRETRIM_OPEN2               1053
#define IDC_POINT_NUMBER                1056
#define IDC_CHECK_EDHJ                  1058
#define IDC_STATIC1                     1060
#define IDC_PRETRIM_OUTFILE             1061
#define IDC_RHYT_TYPE                   1065
#define IDC_RDYT                        1066
#define IDC_RDYT_NO                     1067
#define IDC_RDYT_INFILE                 1068
#define IDC_RDYT_OUTFILE                1069
#define IDC_RDYT_IN                     1071
#define IDC_RDYT_OUT                    1072
#define IDC_K                           1073
#define IDC_FILE_FORM                   1074
#define IDC_FILE_RIVISE                 1076
#define IDC_FILE_INPUT                  1077
#define IDC_INPUT_OPEN                  1078
#define IDC_RIVISE_OPEN                 1079
#define IDC_CHECK_DATA                  1080
#define IDC_OUTPUT_OPEN                 1081
#define IDC_FILE_OUTPUT                 1082
#define IDC_TYPE                        1083
#define IDC_STATIC_1                    1085
#define IDC_EDIT_FIRST                  1086
#define IDC_PARA_FILE                   1087
#define IDC_DATA_FILE                   1088
#define IDC_IS_ZERO                     1089
#define IDC_PARA_OPEN                   1090
#define IDC_DATA_OPRN                   1091
#define IDC_FILE_OPEN                   1092
#define IDC_DATA_CHECK                  1093
#define IDC_FORM                        1094
#define IDC_LINE_NO                     1095
#define IDC_POINT_NO                    1096
#define IDC_MY_PATH                     1097
#define IDC_OPEN                        1098
#define IDC_DATA_OPEN                   1099
#define IDC_CENTER_DEEP                 1100
#define IDC_LINE_DIS                    1101
#define IDC_POINT_DIS                   1102
#define IDC_REST_ROU                    1103
#define IDC_FILE_OUT                    1104
#define IDC_DRAGGING                    1320
#define IDC_HANDCUR                     3010
#define ID_SMALL                        32771
#define ID_MENUITEM32774                32774
#define ID_MENUITEM32775                32775
#define ID_GRAPHER_DRAW                 32775
#define ID_1P1                          32776
#define ID_QT                           32776
#define ID_1P2                          32777
#define ID_2                            32778
#define ID_MEG_1                        32779
#define ID_MEG_2                        32780
#define ID_MEG_3                        32781
#define ID_EDHJ                         32782
#define ID_UP_EXTEND                    32783
#define ID_PRE_TRIM                     32783
#define ID_DOWN_EXTEND                  32784
#define ID_ABNOMAL_CACU                 32784
#define ID_ABNORMAL_CACU                32784
#define ID_SUFFER_DRAW                  32785
#define ID_BZT                          32786
#define ID_MEG_UPEX                     32787
#define ID_MAG_UPEX2                    32787
#define ID_MEG_DOWNEX                   32788
#define ID_SHOW_HIDE_IEBAR              32789
#define ID2                             32793
#define ID6                             32797
#define ID_TITLE                        32798
#define ID_STATIC_TEST                  32799
#define ID_DYNAMIC_TWO                  32800
#define ID_DYNAMIC_MULTI                32801
#define ID_COHERENCE_TEST               32802
#define ID_VALUE_RIVISE                 32803
#define ID_UP_EXTEND2                   32804
#define ID_DOWN_EXTEND2                 32805
#define ID_UP_EXTEND3                   32806
#define ID_DOWN_EXTEND3                 32807
#define ID_VXZ2                         32808
#define ID_VZZ2                         32809
#define ID_VZZZ2                        32810
#define ID_VXZ3                         32811
#define ID_VZZ3                         32812
#define ID_VZZZ3                        32813
#define ID_DIQIAN                       32814
#define ID_GRAVITY_QT                   32816
#define ID_MAG_DOWNEX2                  32818
#define ID_MAG_UPEX3                    32819
#define ID_MAG_DOWNEX3                  32820
#define ID_STATIC_TESTMAG               32821
#define ID_DYNAMIC_TWOMAG               32823
#define ID_DYNAMIC_MULMAG               32824
#define ID_COHERENCE_MAG                32825
#define ID_VALUETEST_MAG                32826
#define IDQQ                            32827
#define ID_MAG_VXZ2                     32828
#define ID_MAG_VZZ2                     32829
#define ID_MAG_VZZZ2                    32830
#define ID_MAG_VXZ3                     32831
#define ID_MAG_VZZ3                     32832
#define ID_MAG_VZZZ3                    32833
#define ID_MY_FILE_OPEN                 32834
#define ID_DATA_REVIEW                  32840
#define ID_NOTICE                       32841
#define ID_DRAW_EL                      32842
#define ID_DRAW_LINE                    32843
#define ID_DRAW_RE                      32844
#define ID_POINTER                      32847
#define ID_MYDRAW                       32848
#define ID_THREE_OP                     32849
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_RENAMEITEM               50002
#define ID_GFX_REMOVEITEM               50003
#define ID_INDICATOR_TIME               59142
#define ID_REVIEW_MAG                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
